export const EMERALD_GHOST_SHIP = Object.freeze({
  id: 'fantasma-esmeralda',
  name: 'Fantasma Esmeralda',
  description: 'Embarcação espectral das Águas Escuras.',
  status: 'npc-only',
  playable: false,
  npcEnabled: true,
  shopEnabled: false,
  rewardEnabled: false,
  cannonSlots: 0,
  sprite: Object.freeze({
    path: '../../assets/ships/verde_fantasma.webp',
    frameWidth: 400,
    frameHeight: 400,
    columns: 4,
    rows: 4,
    frameCount: 16,
    angleStepDegrees: 22.5,
    headingZero: 'north',
    clockwise: true,
    framesByHeading: Object.freeze([4,5,6,7,8,9,10,11,12,13,14,15,0,1,2,3]),
  }),
  spectralEffect: Object.freeze({
    enabled: true,
    glowRadius: 1.18,
    coreIntensity: 0.72,
    haloIntensity: 0.92,
    pulseSpeed: 0.72,
    wispIntensity: 0.58,
    distortion: 0.22,
  }),
});
